# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-synthetics-recorder
  description: Buildkite Pipeline for Releasing the synthetics-recorder
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/synthetics-recorder-release
spec:
  type: buildkite-pipeline
  owner: group:observablt-robots
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: synthetics-recorder-release
      description: Buildkite Pipeline for Releasing the synthetics-recorder
    spec:
      repository: elastic/synthetics-recorder
      pipeline_file: '.buildkite/release.yml'
      allow_rebuilds: true
      cancel_intermediate_builds: false
      skip_intermediate_builds: false
      provider_settings:
        build_branches: false
        build_tags: true
        filter_condition: | # Eg v100.100.100 but skip v100.100.100.1 or v100.100.100-rc
          build.tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
        filter_enabled: true
      teams:
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        uptime:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
