---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Package :package:"
    command: ".buildkite/scripts/package.sh"
    agents:
      provider: orka
      imagePrefix: generic-13-ventura-x64

  - wait: ~

  - label: "Sign linux :linux:"
    command: "true"

  - label: Sign artifacts
    trigger: unified-release-gpg-signing
    # NOTE: If you change 'key: sign-service' then change .buildkite/scripts/download-signed-artifacts.sh
    key: sign-service
    build:
      env:
        INPUT_PATH: buildkite://

  - label: "Sign macos :mac:"
    command: "true"

  - label: "Sign windows :windows:"
    command: "true"

  - wait: ~

  - label: Download signed artifacts
    commands:
      - .buildkite/scripts/download-signed-artifacts.sh
      - .buildkite/scripts/download-signed-artifacts.sh | buildkite-agent pipeline upload

  - label: "Publish S3 Artifacts :s3:"
    command: "true"

  - wait: ~

  - label: "Publish GitHub Release :github:"
    command: "true"

# Figure out how to notify releases (maybe subscribe the slack channel to the GitHub releases?)
notify:
  - slack: "#on-week-oblt-productivity"
    if: 'build.state != "passed"'
