#!/usr/bin/env bash
##  This script prepares the secret context
##
##  NOTE: *_SECRET or *_TOKEN env variables are masked, hence if you'd like to avoid any
##        surprises please use the suffix _SECRET or _TOKEN for those values that contain
##        any sensitive data. Buildkite can mask those values automatically

set -eo pipefail

# If not Git tag release then DRY_RUN=true
DRY_RUN=true
if [ -n "${BUILDKITE_TAG}" ] ; then
  DRY_RUN=false
fi
export DRY_RUN

# Upload should only allow configuring the Buildkite Token ih the pre-command.
if [[ "$BUILDKITE_COMMAND" =~ .*"upload".* ]]; then
  echo "Skipped pre-command when running the Upload pipeline"
  # NOTE: exit 0 with the pre-command does not work!
else
  set +x
  set +e
  echo "~~~ Install nvm"
  touch ~/.zshrc  # See https://github.com/nvm-sh/nvm?tab=readme-ov-file#troubleshooting-on-macos
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi
